### PR TITLE
housekeeping

### PR DESCRIPTION
**Pull request by ArnoldZokas**

### CODE REVIEW

**Comment by ArnoldZokas** [comment]
@matteofigus review pls. I am switching to semaphore, so ignore travis errors.

**Comment by matteofigus** [comment]
Hi, 
1) I can't see the tests executed in Semaphore, just ran "npm i"
2) I would ensure we add a kind of a CHANGELOG to signal we are dropping support for old node versions as there are consumers using that (and would trigger a major version change when publishing)

**Comment by matteofigus** [comment]
3) This is in opentable github - if you want to switch to semaphore can we set it up in the opentable org please?

**Comment by ArnoldZokas** [comment]
@matteofigus I will kill this PR and start over.

**Comment by ArnoldZokas** [comment]
Why are people still on 0.10? It's 20-fucking-16.

**Comment by matteofigus** [comment]
I have nothing against killing support, just saying I would like a changelog

**Pull request closed without merging**
